name: HashNav
author: Xunnamius
category: Utilities
tags: [hash, navigation, ajax, watcher]
docs: http://github.com/Xunnamius/HashNav/blob/master/README.md
demo: http://xunnamius.github.com/HashNav/
current: 0.8