name: HashNav
author: Xunnamius
category: Utilities
current: 0.97
tags: [hash, navigation, ajax, browser, utility]
docs: https://github.com/Xunnamius/HashNav/blob/master/Docs/Documentation.md
demo: http://xunnamius.github.com/HashNav/